import requests
from requests.auth import HTTPBasicAuth
import json

email = "samarthj204@gmail.com"
api_token = "ATATT3xFfGF0yuxFEsLUq6z4w5mgrkcc-YCRPn_RhsA0VK-CCPM0HVq0ljxCIJx9fNJtq6KXRK5ESJJ5riB5m7GBW0o_GT0Bf3y2boeyza1WeYKaMqWjXuKr-RQ1MXD9BVYvA1CJ7D_xhog-G3MQpkuLD-J7i2QIzLSvxK6K3NNOlf1Xklr1cgw=4262CF74"
domain = "samarthj204.atlassian.net"  # your site name
project_key = "KAN"  # project key from Jira

def create_jira_task(summary, description="Generated by AI agent", due_date=None):
    url = f"https://{domain}/rest/api/3/issue"

    headers = {
        "Accept": "application/json",
        "Content-Type": "application/json"
    }

    payload = json.dumps({
        "fields": {
            "project": {"key": project_key},
            "summary": summary,
            "description": description,
            "issuetype": {"name": "Task"},
        }
    })

    response = requests.post(
        url,
        data=payload,
        headers=headers,
        auth=HTTPBasicAuth(email, api_token)
    )

    if response.status_code == 201:
        print("✅ Created Jira issue:", response.json()["key"])
    else:
        print("❌ Failed:", response.status_code, response.text)
if __name__ == "__main__":
    create_jira_task("Test Task from Agent", "This task was generated during testing.")
